services:
  #redpanda.lightweight kakfa server
  redpanda:
    image: redpandadata/redpanda:v25.3.9
    command:
      - redpanda start --smp 1 --reserve-memory 0M --overprovisioned --node-id 1
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - 9092:9092

  #Minio. S3 compatible object store
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

  #postgres
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=sec_analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  #flink cluster
  jobmanager:
    image: flink-streaming
    build: .
    ports: ["8081:8081"]
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        s3.endpoint: http://minio:9000
        s3.access-key: admin
        s3.secret-key: password
        s3.path.style.access: true

  taskmanager:
    image: flink-streaming
    depends_on: [jobmanager]
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2